#!/bin/bash

# format everything
pnpm format
echo "All files formatted."

# lint, test, build changed projects
pnpm pre-commit
echo "All affected projects linted, tested, and built successfully."

# TODO: only add changes if the files were formatted
# add changes to this commit 
git add .